[package]
name = "img2fbm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
clap = { version = "4.3.14", features = ["derive"] }
rand = "0.8.5"
regex = "1"
indicatif = "0.17.5"
