[package]
name = "img2fbm"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.2"
clap = { version = "4.3.19", features = ["derive"] }
indicatif = "0.17.5"
